#!/usr/bin/env python3
"""Scrape the Conecta gov.br catalog listing into catalog/conecta.yaml.

The Conecta catalog page is static HTML with one <a class="api-card"> per API.
All Conecta APIs require adhesion as a public-sector entity, so every entry is
generated with status: requires_public_entity and no callable base_url yet.

Usage: python scripts/scrape_conecta.py [output.yaml]
"""

import re
import sys
import urllib.request
from pathlib import Path

import yaml

CATALOG_URL = "https://www.gov.br/conecta/catalogo/"
CARD_RE = re.compile(
    r'<a href="(?P<url>https://www\.gov\.br/conecta/catalogo/apis/[^"]+)"\s+class="api-card">'
    r".*?<p class=\"title\">(?P<title>.*?)</p>"
    r".*?<p class=\"desc\">(?P<desc>.*?)</p>"
    r"(?P<rest>.*?)</a>",
    re.DOTALL,
)
ORGAO_RE = re.compile(r'class="orgao".*?<span class="orgao-title">(.*?)</span>', re.DOTALL)
TAG_RE = re.compile(r'<span class="tag \w+">(.*?)</span>')


def clean(text: str) -> str:
    text = re.sub(r"<[^>]+>", "", text)
    return re.sub(r"\s+", " ", text).strip()


def main() -> None:
    out_path = Path(sys.argv[1] if len(sys.argv) > 1 else "catalog/conecta.yaml")
    with urllib.request.urlopen(CATALOG_URL, timeout=30) as resp:
        html = resp.read().decode("utf-8")

    seen: set[str] = set()
    apis = []
    for m in CARD_RE.finditer(html):
        slug = m.group("url").rstrip("/").rsplit("/", 1)[-1]
        if slug in seen:
            continue
        seen.add(slug)
        orgao = ORGAO_RE.search(m.group("rest"))
        tags = [clean(t).lower() for t in TAG_RE.findall(m.group("rest"))]
        apis.append(
            {
                "id": f"conecta-{slug}",
                "name": clean(m.group("title")),
                "provider": clean(orgao.group(1)) if orgao else "Conecta gov.br",
                "category": "conecta",
                "status": "requires_public_entity",
                "auth": "oauth2_client_credentials",
                "docs_url": m.group("url"),
                "description": clean(m.group("desc")),
                "tags": tags,
                "notes": (
                    "Requires adhesion to Conecta gov.br as a public-sector entity. "
                    "Gateway: https://apigateway.conectagov.estaleiro.serpro.gov.br "
                    "(per-API path; see docs_url for the adhesion process and Swagger)."
                ),
            }
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("# Generated by scripts/scrape_conecta.py — do not edit by hand.\n")
        f.write(f"# Source: {CATALOG_URL}\n")
        yaml.safe_dump({"apis": apis}, f, allow_unicode=True, sort_keys=False, width=100)
    print(f"{len(apis)} APIs written to {out_path}")


if __name__ == "__main__":
    main()
